package com.github.forax.javawebcompiler;

import javax.tools.DiagnosticCollector;
import javax.tools.JavaFileObject;
import javax.tools.SimpleJavaFileObject;
import javax.tools.ToolProvider;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;

/**
 * Utility class responsible for compiling Java source code in memory.
 * <p>
 * This class uses the Java Compiler API to compile source code without
 * writing any files to disk. The generated bytecode is captured and stored
 * in a {@link MemoryClassLoader}, allowing dynamic class loading and execution.
 */
public final class Compiler {
  private Compiler(){
      throw new AssertionError("no instances");
  }

  /**
   * Represents a compilation diagnostic (error, warning, etc.).
   *
   * @param line the line number where the issue occurred
   * @param column the column number where the issue occurred
   * @param message the localized diagnostic message
   * @param kind the kind of diagnostic (e.g., ERROR, WARNING)
   */
  record Diagnostic(long line, long column, String message, String kind) {}

  /**
   * Internal result of a compilation task.
   *
   * @param success whether the compilation succeeded
   * @param diagnostics the collected diagnostics from the compiler
   * @param loader the class loader containing compiled bytecode
   */
  private record CompilerResult(boolean success, DiagnosticCollector<Object> diagnostics, MemoryClassLoader loader) {}

  /**
   * Represents a compilation request.
   *
   * @param code the Java source code to compile
   */
  record CompileRequest(String code){
    CompileRequest {
      Objects.requireNonNull(code);
    }
  }


  /**
   * Compiles Java source code in memory and returns compilation diagnostics.
   * <p>
   * If the compilation succeeds, the generated bytecode is stored in the
   * provided {@link MemoryClassLoader}.
   *
   * @param className the fully qualified name of the class to compile
   * @param sourceCode the Java source code
   * @param loader the class loader that will receive compiled classes
   * @return a list of diagnostics (empty if compilation succeeds)
   */
  static List<Diagnostic> compileInMemory(String className, String sourceCode, MemoryClassLoader loader) {
    var compileResult = compileTask(className, sourceCode, loader);
    return compilationResultHandler(compileResult);
  }

  /**
   * Creates and executes a compilation task using the Java Compiler API.
   *
   * @param className the name of the class to compile
   * @param sourceCode the source code to compile
   * @param loader the class loader used to store compiled bytecode
   * @return a {@link CompilerResult} containing compilation status and diagnostics
   * @throws IllegalStateException if the system compiler is not available
   */
  private static CompilerResult compileTask (String className, String sourceCode, MemoryClassLoader loader){
    var compiler = ToolProvider.getSystemJavaCompiler();
    if(compiler == null){
      throw new IllegalStateException("Compiler not available");
    }
    var diagnostics = new DiagnosticCollector<>();
    var fileManager = new MemoryFileManager(compiler.getStandardFileManager(null, null, null), loader);

    var file = new SimpleJavaFileObject(
            URI.create("string:///" + className.replace('.', '/') + JavaFileObject.Kind.SOURCE.extension),
            JavaFileObject.Kind.SOURCE) {
        @Override
        public CharSequence getCharContent(boolean ignoreEncodingErrors) {
            return sourceCode;
        }
    };

    var compilationUnits = List.of(file);
    var task = compiler.getTask(null, fileManager, diagnostics, null, null, compilationUnits);

    var success = task.call();
    return new CompilerResult(success, diagnostics, loader);
  }

  /**
   * Converts the raw compiler diagnostics into a list of {@link Diagnostic}.
   *
   * @param compilerResult the result of the compilation task
   * @return a list of formatted diagnostics (empty if compilation succeeded)
   */
  private static List<Diagnostic> compilationResultHandler(CompilerResult compilerResult){
    var result = new ArrayList<Diagnostic>();
    if (!compilerResult.success) {
      for (var diagnostic : compilerResult.diagnostics.getDiagnostics()) {
        result.add(new Diagnostic(
                diagnostic.getLineNumber(),
                diagnostic.getColumnNumber(),
                diagnostic.getMessage(Locale.FRANCE),
                diagnostic.getKind().name()
        ));
      }
    }

    return result;
  }
}
